# generated by datamodel-codegen:
#   filename:  jesterky.manifest.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel, conint
from enum import Enum
from typing import Any


class ArtifactRef(BaseModel):
    """
    A stable reference to an artifact held in the host `ArtifactStore`.
    """

    content_type: str
    key: str = Field(
        ...,
        description='e.g. `blob/ab12cd`. Opaque to the core; meaningful to the store.',
    )
    size_bytes: conint(ge=0)


class Call(Enum):
    actor = 'actor'


class CallKind1(BaseModel):
    """
    Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].
    """

    actor: str
    call: Call


class Call1(Enum):
    resource_observe = 'resource_observe'


class CallKind2(BaseModel):
    """
    Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].
    """

    call: Call1
    session: str


class Call2(Enum):
    resource_step = 'resource_step'


class CallKind3(BaseModel):
    """
    Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].
    """

    call: Call2
    session: str


class CallKind(RootModel[CallKind1 | CallKind2 | CallKind3]):
    root: CallKind1 | CallKind2 | CallKind3 = Field(
        ...,
        description='Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].',
    )


class Kind(Enum):
    workflow_started = 'workflow_started'


class EventKind1(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind


class Kind1(Enum):
    node_started = 'node_started'


class EventKind2(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind1


class Kind2(Enum):
    node_completed = 'node_completed'


class EventKind3(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind2


class Kind3(Enum):
    map_item_started = 'map_item_started'


class EventKind4(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind3


class Kind4(Enum):
    map_item_completed = 'map_item_completed'


class EventKind5(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind4


class Kind5(Enum):
    map_item_failed = 'map_item_failed'


class EventKind6(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind5


class Kind6(Enum):
    map_completed = 'map_completed'


class EventKind7(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind6


class Kind7(Enum):
    actor_invoked = 'actor_invoked'


class EventKind8(BaseModel):
    """
    An actor/resource call was recorded (see replay manifest).
    """

    kind: Kind7


class Kind8(Enum):
    resource_invoked = 'resource_invoked'


class EventKind9(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind8


class Kind9(Enum):
    session_started = 'session_started'


class EventKind10(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind9


class Kind10(Enum):
    session_resumed = 'session_resumed'


class EventKind11(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind10


class Kind11(Enum):
    checkpoint_created = 'checkpoint_created'


class EventKind12(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind11


class Kind12(Enum):
    semaphore_acquired = 'semaphore_acquired'


class EventKind13(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind12


class Kind13(Enum):
    semaphore_released = 'semaphore_released'


class EventKind14(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind13


class Kind14(Enum):
    message_published = 'message_published'


class EventKind15(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind14


class Kind15(Enum):
    message_available = 'message_available'


class EventKind16(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind15


class Kind16(Enum):
    artifact_emitted = 'artifact_emitted'


class EventKind17(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind16


class Kind17(Enum):
    workflow_completed = 'workflow_completed'


class EventKind18(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind17


class Kind18(Enum):
    workflow_failed = 'workflow_failed'


class EventKind19(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind18


class EventKind(
    RootModel[
        EventKind1
        | EventKind2
        | EventKind3
        | EventKind4
        | EventKind5
        | EventKind6
        | EventKind7
        | EventKind8
        | EventKind9
        | EventKind10
        | EventKind11
        | EventKind12
        | EventKind13
        | EventKind14
        | EventKind15
        | EventKind16
        | EventKind17
        | EventKind18
        | EventKind19
    ]
):
    root: (
        EventKind1
        | EventKind2
        | EventKind3
        | EventKind4
        | EventKind5
        | EventKind6
        | EventKind7
        | EventKind8
        | EventKind9
        | EventKind10
        | EventKind11
        | EventKind12
        | EventKind13
        | EventKind14
        | EventKind15
        | EventKind16
        | EventKind17
        | EventKind18
        | EventKind19
    ) = Field(
        ...,
        description='The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)',
    )


class PathSeg1(BaseModel):
    """
    One segment of a node path. A path alternates named nodes and numeric indices, e.g. `audit_jobs` → `[3]` for the 4th map item. Kept typed (not a string) so that `Index(2) < Index(10)` orders numerically, not lexically.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    node: str


class PathSeg2(BaseModel):
    """
    One segment of a node path. A path alternates named nodes and numeric indices, e.g. `audit_jobs` → `[3]` for the 4th map item. Kept typed (not a string) so that `Index(2) < Index(10)` orders numerically, not lexically.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    index: conint(ge=0)


class PathSeg(RootModel[PathSeg1 | PathSeg2]):
    root: PathSeg1 | PathSeg2 = Field(
        ...,
        description='One segment of a node path. A path alternates named nodes and numeric indices, e.g. `audit_jobs` → `[3]` for the 4th map item. Kept typed (not a string) so that `Index(2) < Index(10)` orders numerically, not lexically.',
    )


class RunStatus(Enum):
    completed = 'completed'
    failed = 'failed'


class Artifact(RootModel[Any | ArtifactRef]):
    root: Any | ArtifactRef = Field(
        ...,
        description='Either an inline small value or a reference to an offloaded one. The runner applies the inline/offload split at a size cap.',
    )


class NodePath(RootModel[list[PathSeg]]):
    """
    Fully-qualified position of a node in a run's dynamic execution tree. Ordering is lexicographic over segments (derived), which is exactly the structural order we want.
    """

    root: list[PathSeg] = Field(
        ...,
        description="Fully-qualified position of a node in a run's dynamic execution tree. Ordering is lexicographic over segments (derived), which is exactly the structural order we want.",
    )


class Addr(BaseModel):
    """
    The structural address of an event — its identity and its sort key.

    Field order matters: `derive(Ord)` compares in declaration order, so the effective ordering is `(node_path, iteration, local_seq)` within a run (`run_id` is constant across a run's events). NEVER add an emission counter.
    """

    iteration: conint(ge=0) = Field(
        ...,
        description='Loop/`while` iteration at this node (0 for non-looping nodes).',
    )
    local_seq: conint(ge=0) = Field(
        ...,
        description='Monotonic sequence WITHIN a single `(node_path, iteration)`, allocated locally by the runner. Two parallel siblings never share a `local_seq` because they have distinct `node_path`s.',
    )
    node_path: NodePath = Field(
        ..., description='Where in the execution tree this event was produced.'
    )
    run_id: str


class Checkpoint(BaseModel):
    """
    A per-session state snapshot (DungeonGrid takes one per turn). `state` may be offloaded to the checkpoint store when large. A `resume_session` node rehydrates from the latest checkpoint for its session.
    """

    addr: Addr
    session: str
    state: Artifact


class Event(BaseModel):
    """
    One event in the stream. `wall_ms` is metadata ONLY — never part of ordering or identity (that is [`Addr`]'s job).
    """

    addr: Addr
    kind: EventKind
    payload: Any
    wall_ms: conint(ge=0)


class ProcessNode(BaseModel):
    """
    One node's contribution to the process tree.
    """

    addr: Addr
    artifacts: list[ArtifactRef] = Field(
        ..., description='Large outputs offloaded to the store.'
    )
    children: list[ProcessNode]
    inputs: Any = Field(
        ..., description='Typed inputs the node received (post-binding-resolution).'
    )
    label: str = Field(
        ..., description='e.g. "map:audit_jobs", "actor:quality_auditor".'
    )
    outputs: Any = Field(..., description='Typed outputs the node produced.')
    score: float | None = Field(
        None,
        description='Optimizer slot: an outcome score, if the actor supplied one. Grades OUTCOMES only.',
    )
    signal: Any | None = Field(
        None, description='Optimizer slot: a wall-safe verifier signal, if any.'
    )


class RecordedOutput(BaseModel):
    """
    What an actor/resource returned, recorded so replay can re-drive without the live model/env (ADR #7). Keyed by [`Addr`] via the `addr` field (kept in a `Vec` rather than a map so the manifest serializes to plain JSON).
    """

    addr: Addr
    artifacts: list[ArtifactRef]
    call: CallKind
    outputs: Any
    score: float | None = None
    signal: Any | None = None


class RunManifest(BaseModel):
    """
    The full record of a run: enough to replay it and to hand an optimizer a structured process object. Produced by the runner; consumed by the CLI/Stack visualizer, the replay engine, and the optimizers.
    """

    args: Any
    checkpoints: list[Checkpoint] | None = Field(
        [],
        description='Session state snapshots taken during the run.',
        validate_default=True,
    )
    events: list[Event] = Field(
        ...,
        description='The event stream, in emission order. Sort by `event.addr` for the canonical order (replay compares against that).',
    )
    recorded: list[RecordedOutput] = Field(
        ..., description='Recorded impure outputs, one per actor/resource invocation.'
    )
    run_id: str
    spec_hash: str = Field(
        ...,
        description='The canonical graph hash this run was produced from (ADR #5). A replay asserts it re-drives the SAME topology.',
    )
    status: RunStatus
    trace: ProcessNode | None = Field(
        None, description='The process tree for optimizer consumption.'
    )
    workflow_name: str


ProcessNode.model_rebuild()
