# generated by datamodel-codegen:
#   filename:  jesterky.manifest.schema.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel, conint
from enum import Enum
from typing import Any


class ArtifactRef(BaseModel):
    """
    A stable reference to an artifact held in the host `ArtifactStore`.
    """

    content_type: str
    key: str = Field(
        ...,
        description='e.g. `blob/ab12cd`. Opaque to the core; meaningful to the store.',
    )
    size_bytes: conint(ge=0)


class BudgetEtaMode1(Enum):
    """
    Do not show or compute ETA forecasts.
    """

    off = 'off'


class BudgetEtaMode2(Enum):
    """
    Show only the soonest-to-exhaust cap.
    """

    nearest_only = 'nearest_only'


class BudgetEtaMode3(Enum):
    """
    Show every cap that has a finite forecast (default).
    """

    all = 'all'


class BudgetEtaMode(RootModel[BudgetEtaMode1 | BudgetEtaMode2 | BudgetEtaMode3]):
    root: BudgetEtaMode1 | BudgetEtaMode2 | BudgetEtaMode3 = Field(
        ..., description='How ETA lines are composed on the terminal panel.'
    )


class BudgetKind1(Enum):
    """
    Impure actor invocations (model turns, env-coupled hero acts, …).
    """

    actor_calls = 'actor_calls'


class BudgetKind2(Enum):
    """
    Total tokens (in+out) observed on the live bus / recorded usage.
    """

    tokens = 'tokens'


class BudgetKind3(Enum):
    """
    Wall-clock seconds since the host started the run.
    """

    wall_seconds = 'wall_seconds'


class BudgetKind(RootModel[BudgetKind1 | BudgetKind2 | BudgetKind3]):
    root: BudgetKind1 | BudgetKind2 | BudgetKind3 = Field(
        ..., description='What resource is being capped.'
    )


class BudgetState(Enum):
    """
    How close a budget is to its cap.
    """

    ok = 'ok'
    warning = 'warning'
    exhausted = 'exhausted'
    unlimited = 'unlimited'
    unknown = 'unknown'


class BudgetVizConfig(BaseModel):
    """
    Terminal / panel rendering knobs for budgets.
    """

    enabled: bool | None = Field(
        True,
        description='Master switch (default true). When false, no budget lines are drawn.',
    )
    short_labels: bool | None = Field(
        True,
        description='Use short labels (`calls`/`tok`/`wall`) instead of full kind names.',
    )
    show_eta: bool | None = Field(
        True, description='Show the ETA line (`ETA calls 3m24s · …`).'
    )
    show_nearest_tag: bool | None = Field(
        True, description='Append `nearest <kind>` on the ETA line.'
    )
    show_progress: bool | None = Field(
        True, description='Show the progress line (`calls 4/64 (6%) · …`).'
    )


class Call(Enum):
    actor = 'actor'


class CallKind1(BaseModel):
    """
    Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].
    """

    actor: str
    call: Call


class Call1(Enum):
    resource_observe = 'resource_observe'


class CallKind2(BaseModel):
    """
    Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].
    """

    call: Call1
    session: str


class Call2(Enum):
    resource_step = 'resource_step'


class CallKind3(BaseModel):
    """
    Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].
    """

    call: Call2
    session: str


class CallKind(RootModel[CallKind1 | CallKind2 | CallKind3]):
    root: CallKind1 | CallKind2 | CallKind3 = Field(
        ...,
        description='Which impure call produced a [`RecordedOutput`]. Lets a single recorded stream serve both [`crate`]-level actor replay AND resource (env) replay: the `ReplayActor` matches `Actor` entries, the `ReplayResource` matches `ResourceObserve`/`ResourceStep` entries, both keyed by [`Addr`].',
    )


class Kind(Enum):
    workflow_started = 'workflow_started'


class EventKind1(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind


class Kind1(Enum):
    node_started = 'node_started'


class EventKind2(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind1


class Kind2(Enum):
    node_completed = 'node_completed'


class EventKind3(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind2


class Kind3(Enum):
    map_item_started = 'map_item_started'


class EventKind4(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind3


class Kind4(Enum):
    map_item_completed = 'map_item_completed'


class EventKind5(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind4


class Kind5(Enum):
    map_item_failed = 'map_item_failed'


class EventKind6(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind5


class Kind6(Enum):
    map_completed = 'map_completed'


class EventKind7(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind6


class Kind7(Enum):
    actor_invoked = 'actor_invoked'


class EventKind8(BaseModel):
    """
    An actor/resource call was recorded (see replay manifest).
    """

    kind: Kind7


class Kind8(Enum):
    resource_invoked = 'resource_invoked'


class EventKind9(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind8


class Kind9(Enum):
    session_started = 'session_started'


class EventKind10(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind9


class Kind10(Enum):
    session_resumed = 'session_resumed'


class EventKind11(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind10


class Kind11(Enum):
    checkpoint_created = 'checkpoint_created'


class EventKind12(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind11


class Kind12(Enum):
    semaphore_acquired = 'semaphore_acquired'


class EventKind13(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind12


class Kind13(Enum):
    semaphore_released = 'semaphore_released'


class EventKind14(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind13


class Kind14(Enum):
    message_published = 'message_published'


class EventKind15(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind14


class Kind15(Enum):
    message_available = 'message_available'


class EventKind16(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind15


class Kind16(Enum):
    artifact_emitted = 'artifact_emitted'


class EventKind17(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind16


class Kind17(Enum):
    workflow_completed = 'workflow_completed'


class EventKind18(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind17


class Kind18(Enum):
    workflow_failed = 'workflow_failed'


class EventKind19(BaseModel):
    """
    The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)
    """

    kind: Kind18


class EventKind(
    RootModel[
        EventKind1
        | EventKind2
        | EventKind3
        | EventKind4
        | EventKind5
        | EventKind6
        | EventKind7
        | EventKind8
        | EventKind9
        | EventKind10
        | EventKind11
        | EventKind12
        | EventKind13
        | EventKind14
        | EventKind15
        | EventKind16
        | EventKind17
        | EventKind18
        | EventKind19
    ]
):
    root: (
        EventKind1
        | EventKind2
        | EventKind3
        | EventKind4
        | EventKind5
        | EventKind6
        | EventKind7
        | EventKind8
        | EventKind9
        | EventKind10
        | EventKind11
        | EventKind12
        | EventKind13
        | EventKind14
        | EventKind15
        | EventKind16
        | EventKind17
        | EventKind18
        | EventKind19
    ) = Field(
        ...,
        description='The closed set of event families. Payload detail rides in [`Event::payload`] as a typed value; this enum is the stable vocabulary consumers switch on. (Taxonomy adapted from `rlm/rlm_event_streaming_plan.md`, retyped — §11.)',
    )


class ForecastConfidence(Enum):
    """
    Forecast confidence (interval width).
    """

    high = 'high'
    medium = 'medium'
    low = 'low'
    unknown = 'unknown'


class Kind19(Enum):
    ledger_pred = 'ledger_pred'


class GoalSpec1(BaseModel):
    """
    Met when the ledger value at `path` deep-equals `equals`.
    """

    id: str = Field(..., description='Stable identifier (unique within a plan).')
    label: str | None = Field(
        None,
        description='Optional display name (panel + snapshot). Defaults to [`Self::id`].',
    )
    required: bool | None = Field(
        True,
        description='Required goals gate the run state and `fail_on_unmet` (default true). Non-required goals record progress only and never block.',
    )
    show_progress: bool | None = Field(
        True, description='Include this goal on the progress viz line (default true).'
    )
    equals: Any
    kind: Kind19
    path: str


class Kind20(Enum):
    metric_threshold = 'metric_threshold'


class GoalSpec2(BaseModel):
    """
    Met when the numeric ledger value at `path` is `>= min`. Progress = `value/min`.
    """

    id: str = Field(..., description='Stable identifier (unique within a plan).')
    label: str | None = Field(
        None,
        description='Optional display name (panel + snapshot). Defaults to [`Self::id`].',
    )
    required: bool | None = Field(
        True,
        description='Required goals gate the run state and `fail_on_unmet` (default true). Non-required goals record progress only and never block.',
    )
    show_progress: bool | None = Field(
        True, description='Include this goal on the progress viz line (default true).'
    )
    kind: Kind20
    min: float
    path: str


class GoalSpec(RootModel[GoalSpec1 | GoalSpec2]):
    root: GoalSpec1 | GoalSpec2 = Field(..., description='One declared goal on a run.')


class GoalState1(Enum):
    """
    Predicate satisfied.
    """

    met = 'met'


class GoalState2(Enum):
    """
    Predicate evaluated but not satisfied.
    """

    unmet = 'unmet'


class GoalState3(Enum):
    """
    Path missing or wrong type — cannot evaluate.
    """

    unknown = 'unknown'


class GoalState(RootModel[GoalState1 | GoalState2 | GoalState3]):
    root: GoalState1 | GoalState2 | GoalState3 = Field(
        ..., description='Whether a goal (or the whole run) is satisfied.'
    )


class GoalStatus(BaseModel):
    """
    Result of evaluating one goal against the ledger.
    """

    detail: str = Field(
        ..., description='Human-readable evaluation (`summary.score 0.72 < min 0.80`).'
    )
    id: str
    kind: str = Field(..., description='`ledger_pred` / `metric_threshold`.')
    label: str
    observed: Any | None = Field(
        None,
        description="The observed ledger value at the goal's path (echoed for consumers).",
    )
    progress: float = Field(
        ...,
        description='Partial credit in `[0, 1]`: `1.0` when met, `value/min` for a threshold, `0.0` for an unmet predicate, `0.0` when unknown.',
    )
    required: bool
    show_progress: bool
    state: GoalState


class GoalVizConfig(BaseModel):
    """
    Terminal / panel rendering knobs for goals.
    """

    enabled: bool | None = Field(
        True,
        description='Master switch (default true). When false, no goal line is drawn.',
    )
    short_labels: bool | None = Field(
        True, description='Use short labels (goal id) instead of the full label.'
    )
    show_progress: bool | None = Field(
        True,
        description='Show the per-goal progress line (`goals 1/2 met · quality 0.72/0.80`).',
    )


class InvariantCheck(BaseModel):
    """
    One structural invariant checked over a finished [`RunManifest`].
    """

    detail: str = Field(
        ..., description='Human-readable evidence (counts, the offending addr, …).'
    )
    name: str = Field(
        ...,
        description='Stable check id (e.g. `unique_event_addrs`, `map:scan_jobs.over_matches_total`).',
    )
    ok: bool


class InvariantReport(BaseModel):
    """
    The manifest self-check report. `all_ok` is the AND of every check.
    """

    all_ok: bool
    checks: list[InvariantCheck]


class PathSeg1(BaseModel):
    """
    One segment of a node path. A path alternates named nodes and numeric indices, e.g. `audit_jobs` → `[3]` for the 4th map item. Kept typed (not a string) so that `Index(2) < Index(10)` orders numerically, not lexically.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    node: str


class PathSeg2(BaseModel):
    """
    One segment of a node path. A path alternates named nodes and numeric indices, e.g. `audit_jobs` → `[3]` for the 4th map item. Kept typed (not a string) so that `Index(2) < Index(10)` orders numerically, not lexically.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    index: conint(ge=0)


class PathSeg(RootModel[PathSeg1 | PathSeg2]):
    root: PathSeg1 | PathSeg2 = Field(
        ...,
        description='One segment of a node path. A path alternates named nodes and numeric indices, e.g. `audit_jobs` → `[3]` for the 4th map item. Kept typed (not a string) so that `Index(2) < Index(10)` orders numerically, not lexically.',
    )


class RunStatus(Enum):
    completed = 'completed'
    failed = 'failed'


class RunStopReason(Enum):
    completed = 'completed'
    node_failed = 'node_failed'
    goal_unmet = 'goal_unmet'
    budget_exhausted = 'budget_exhausted'


class Artifact(RootModel[Any | ArtifactRef]):
    root: Any | ArtifactRef = Field(
        ...,
        description='Either an inline small value or a reference to an offloaded one. The runner applies the inline/offload split at a size cap.',
    )


class BudgetCap(BaseModel):
    """
    One declared cap on a run.
    """

    hard: bool | None = Field(
        False,
        description='When true, exceeding the cap fails the run if [`BudgetPlan::fail_on_hard_exhaust`].',
    )
    kind: BudgetKind
    label: str | None = Field(
        None,
        description='Optional display name (panel + snapshot). Defaults to [`BudgetKind::as_str`].',
    )
    max: float = Field(..., description='Hard ceiling; must be > 0.')
    show_eta: bool | None = Field(
        True,
        description='Include this cap on the ETA viz line when a forecast exists (default true).',
    )
    show_progress: bool | None = Field(
        True, description='Include this cap on the progress viz line (default true).'
    )
    warning_percent: float | None = Field(
        None,
        description='Per-cap warning threshold override (percent of cap). Falls back to plan default.',
    )


class BudgetEtaConfig(BaseModel):
    """
    ETA / burn-rate forecast knobs (host metering + engine).
    """

    enabled: bool | None = Field(
        True, description='Master switch for ETA forecasting (default true).'
    )
    min_wall_secs: float | None = Field(
        1.0,
        description='Minimum wall seconds before burn-rate ETA is trusted (default 1.0).',
    )
    mode: BudgetEtaMode | None = Field(
        'all', description='Which ETAs to surface on the panel.', validate_default=True
    )
    sample_interval_secs: float | None = Field(
        0.45, description='Host sampling cadence hint for live follow (default 0.45s).'
    )


class BudgetForecast(BaseModel):
    """
    ETA to exhaust one budget from observed burn rate.

    **Not** “time until the workflow finishes” — see module docs.
    """

    confidence: ForecastConfidence
    model: str
    rate_per_second: float | None = None
    sample_count: conint(ge=0)
    seconds_to_limit: float | None = None
    seconds_to_limit_high: float | None = None
    seconds_to_limit_low: float | None = None


class BudgetPlan(BaseModel):
    """
    Full budget configuration for a workflow run (part of [`crate::topology::RunPlan`]).

    This is the **typed JSON interface**: serialize/deserialize as `runplan.budgets`.
    """

    caps: list[BudgetCap] | None = Field(
        [],
        description='Caps by dimension. Empty plan ⇒ no metering / no panel lines.',
        validate_default=True,
    )
    eta: BudgetEtaConfig | None = Field(
        {
            'enabled': True,
            'min_wall_secs': 1.0,
            'mode': 'all',
            'sample_interval_secs': 0.45,
        },
        description='ETA forecast configuration.',
        validate_default=True,
    )
    fail_on_hard_exhaust: bool | None = Field(
        True, description='Fail the run when a `hard` cap is exhausted (default true).'
    )
    viz: BudgetVizConfig | None = Field(
        {
            'enabled': True,
            'short_labels': True,
            'show_eta': True,
            'show_nearest_tag': True,
            'show_progress': True,
        },
        description='Terminal panel configuration.',
        validate_default=True,
    )
    warning_percent: float | None = Field(
        80.0,
        description='Default warning threshold as percent of cap (0–100). Default 80.',
    )


class BudgetStatus(BaseModel):
    """
    Progress + forecast for one declared cap.
    """

    forecast: BudgetForecast
    hard: bool
    kind: BudgetKind
    label: str = Field(..., description='Effective display label (from cap or kind).')
    max: float
    remaining: float
    reserved: float | None = 0.0
    show_eta: bool
    show_progress: bool
    spent: float
    state: BudgetState
    unit: str
    used_percent: float = Field(..., description='Percent of cap used.')
    utilization: float = Field(
        ..., description='`spent / max` in \\[0, ∞); values ≥ 1 mean exhausted.'
    )


class GoalPlan(BaseModel):
    """
    Full goal configuration for a workflow run (part of [`crate::topology::RunPlan`]).

    This is the **typed JSON interface**: serialize/deserialize as `runplan.goals`.
    """

    cancel_in_flight: bool | None = Field(
        False,
        description='Future control-plane knob: when true, hosts/runners may cancel queued in-flight map work after success wrap-up. Default false preserves v1 entrypoint-skip semantics.',
    )
    fail_on_unmet: bool | None = Field(
        True,
        description='Fail the run when a `required` goal is still unmet at run end. Default true.',
    )
    finalize: str | None = Field(
        None,
        description='Optional finalize node id to run on success wrap-up. Recorded in v1; runner wiring is a follow-up (see `docs/GOALS.md`).',
    )
    goals: list[GoalSpec] | None = Field(
        [],
        description='Declared goals. Empty plan ⇒ no evaluation / no panel line.',
        validate_default=True,
    )
    terminate_on_met: bool | None = Field(
        True,
        description='When every required goal is met, allow the runner to skip remaining entrypoints (early success wrap-up). Default true.',
    )
    viz: GoalVizConfig | None = Field(
        {'enabled': True, 'short_labels': True, 'show_progress': True},
        description='Terminal panel configuration.',
        validate_default=True,
    )


class GoalSnapshot(BaseModel):
    """
    Full goal projection for a run (live follow + final manifest).
    """

    items: list[GoalStatus]
    plan: GoalPlan = Field(
        ...,
        description='Plan knobs used for this projection (echoed for consumers / viz).',
    )
    required_met: conint(ge=0)
    required_total: conint(ge=0)
    run_id: str
    schema_version: str
    state: GoalState = Field(
        ..., description='`met` iff every required goal is met; else `unmet`.'
    )
    terminated_early: bool | None = Field(
        False,
        description='Set by the host/runner when it stopped remaining work because the goals were met. The pure engine always emits `false`.',
    )


class NodePath(RootModel[list[PathSeg]]):
    """
    Fully-qualified position of a node in a run's dynamic execution tree. Ordering is lexicographic over segments (derived), which is exactly the structural order we want.
    """

    root: list[PathSeg] = Field(
        ...,
        description="Fully-qualified position of a node in a run's dynamic execution tree. Ordering is lexicographic over segments (derived), which is exactly the structural order we want.",
    )


class Addr(BaseModel):
    """
    The structural address of an event — its identity and its sort key.

    Field order matters: `derive(Ord)` compares in declaration order, so the effective ordering is `(node_path, iteration, local_seq)` within a run (`run_id` is constant across a run's events). NEVER add an emission counter.
    """

    iteration: conint(ge=0) = Field(
        ...,
        description='Loop/`while` iteration at this node (0 for non-looping nodes).',
    )
    local_seq: conint(ge=0) = Field(
        ...,
        description='Monotonic sequence WITHIN a single `(node_path, iteration)`, allocated locally by the runner. Two parallel siblings never share a `local_seq` because they have distinct `node_path`s.',
    )
    node_path: NodePath = Field(
        ..., description='Where in the execution tree this event was produced.'
    )
    run_id: str


class BudgetSnapshot(BaseModel):
    """
    Full budget projection for a run (live follow + final manifest).
    """

    items: list[BudgetStatus]
    nearest: BudgetStatus | None = Field(
        None,
        description='Soonest ETA among items that have a finite forecast (when ETA enabled).',
    )
    plan: BudgetPlan = Field(
        ...,
        description='Plan knobs used for this projection (echoed for consumers / viz).',
    )
    run_id: str
    schema_version: str
    state: BudgetState = Field(
        ...,
        description='Aggregate run state: exhausted if any hard item is exhausted, else warning, else ok.',
    )
    wall_secs: float = Field(..., description='Wall seconds used for this snapshot.')


class Checkpoint(BaseModel):
    """
    A per-session state snapshot (DungeonGrid takes one per turn). `state` may be offloaded to the checkpoint store when large. A `resume_session` node rehydrates from the latest checkpoint for its session.
    """

    addr: Addr
    session: str
    state: Artifact


class Event(BaseModel):
    """
    One event in the stream. `wall_ms` is metadata ONLY — never part of ordering or identity (that is [`Addr`]'s job).
    """

    addr: Addr
    kind: EventKind
    payload: Any
    wall_ms: conint(ge=0)


class ProcessNode(BaseModel):
    """
    One node's contribution to the process tree.
    """

    addr: Addr
    artifacts: list[ArtifactRef] = Field(
        ..., description='Large outputs offloaded to the store.'
    )
    children: list[ProcessNode]
    inputs: Any = Field(
        ..., description='Typed inputs the node received (post-binding-resolution).'
    )
    label: str = Field(
        ..., description='e.g. "map:audit_jobs", "actor:quality_auditor".'
    )
    outputs: Any = Field(..., description='Typed outputs the node produced.')
    score: float | None = Field(
        None,
        description='Optimizer slot: an outcome score, if the actor supplied one. Grades OUTCOMES only.',
    )
    signal: Any | None = Field(
        None, description='Optimizer slot: a wall-safe verifier signal, if any.'
    )


class RecordedOutput(BaseModel):
    """
    What an actor/resource returned, recorded so replay can re-drive without the live model/env (ADR #7). Keyed by [`Addr`] via the `addr` field (kept in a `Vec` rather than a map so the manifest serializes to plain JSON).
    """

    addr: Addr
    artifacts: list[ArtifactRef]
    call: CallKind
    outputs: Any
    score: float | None = None
    signal: Any | None = None


class RunManifest(BaseModel):
    """
    The full record of a run: enough to replay it and to hand an optimizer a structured process object. Produced by the runner; consumed by the CLI/Stack visualizer, the replay engine, and the optimizers.
    """

    args: Any
    budgets: BudgetSnapshot | None = Field(
        None,
        description='Formal resource-budget projection (progress + ETA) when the run declared [`crate::topology::RunPlan::budgets`]. Host-metered; optional for back-compat.',
    )
    checkpoints: list[Checkpoint] | None = Field(
        [],
        description='Session state snapshots taken during the run.',
        validate_default=True,
    )
    events: list[Event] = Field(
        ...,
        description='The event stream, in emission order. Sort by `event.addr` for the canonical order (replay compares against that).',
    )
    goals: GoalSnapshot | None = Field(
        None,
        description='Formal goal / work-product projection when the run declared [`crate::topology::RunPlan::goals`]. Evaluated from the final ledger; optional for back-compat.',
    )
    invariants: InvariantReport | None = Field(
        None,
        description='Structural self-checks over this manifest (event-addr identity, no orphaned records, per-map fan/gate consistency). Attached when a trace exists. A failing check indicates a runner/manifest bug, not a workload failure.',
    )
    recorded: list[RecordedOutput] = Field(
        ..., description='Recorded impure outputs, one per actor/resource invocation.'
    )
    run_id: str
    spec_hash: str = Field(
        ...,
        description='The canonical graph hash this run was produced from (ADR #5). A replay asserts it re-drives the SAME topology.',
    )
    status: RunStatus
    stop_reason: RunStopReason | None = Field(
        'completed',
        description='Machine-readable terminal reason; consumers should not parse `WorkflowFailed.payload.error`.',
    )
    trace: ProcessNode | None = Field(
        None, description='The process tree for optimizer consumption.'
    )
    workflow_name: str


ProcessNode.model_rebuild()
