# generated by datamodel-codegen:
#   filename:  jesterky.schema.json

from __future__ import annotations
from pydantic import BaseModel, Field, RootModel, conint
from enum import Enum


class Limit(BaseModel):
    """
    A named concurrency budget. Enforced by the runner; `permits` bounds how many holders may hold it at once.
    """

    name: str
    permits: conint(ge=0)


class Kind(Enum):
    program = 'program'


class Kind1(Enum):
    reduce = 'reduce'


class Kind2(Enum):
    actor = 'actor'


class Kind3(Enum):
    map = 'map'


class Kind4(Enum):
    for_each = 'for_each'


class Kind5(Enum):
    while_ = 'while'


class Kind6(Enum):
    branch = 'branch'


class Kind7(Enum):
    session_group = 'session_group'


class Kind8(Enum):
    resume_session = 'resume_session'


class Ref(RootModel[str]):
    root: str = Field(
        ...,
        description='A reference into run state, resolved by the ledger at execution time. Kept a newtype over String in the skeleton; M0 replaces the inner form with a parsed `{ source, path }` so resolution is total and checkable.',
    )


class Verbosity(Enum):
    """
    Per-run event verbosity (adapted from `rlm_event_streaming_plan.md`, §11).
    """

    minimal = 'minimal'
    standard = 'standard'
    verbose = 'verbose'


class Node1(BaseModel):
    """
    Pure, deterministic, in-process op (e.g. `quality.expand`). Re-run on replay — NOT recorded (ADR #7). Resolved from the program registry.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    kind: Kind
    op: str


class Node2(BaseModel):
    """
    Pure aggregation over a collection (a program that folds `results`).
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    kind: Kind1
    op: str


class Node3(BaseModel):
    """
    A host actor call (a model, a subprocess). Impure → recorded for replay.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    actor: str
    kind: Kind2


class Node7(BaseModel):
    """
    Take `then` if `cond` is truthy, else `otherwise`.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    cond: Ref
    kind: Kind6
    otherwise: str | None = None
    then: str


class RunPlan(BaseModel):
    """
    Run-level configuration: concurrency budgets and event verbosity. A run may override these via args.runplan (merged by the runner).
    """

    limits: dict[str, conint(ge=0)] | None = Field(
        {},
        description='Named limits → permits. A `map`/`session_group` `limit` names one of these.',
    )
    map_concurrency: conint(ge=0) | None = Field(
        None,
        description='Default parallel width for `map` nodes lacking their own `concurrency`. `None`/`1` = serial (ADR #5).',
    )
    verbosity: Verbosity | None = 'standard'


class WorkflowSpec(BaseModel):
    """
    A whole workflow. `entrypoint` is the ordered list of top-level nodes to run (matches mloky's model). `nodes` is the id → node map.
    """

    entrypoint: list[str]
    name: str
    nodes: dict[str, Node]
    runplan: RunPlan | None = Field(
        {'limits': {}, 'map_concurrency': None, 'verbosity': 'standard'},
        description='Execution budgets/defaults for this workflow.',
        validate_default=True,
    )


class Node4(BaseModel):
    """
    Fan `body` over `over`, binding each element as `item_as`. `concurrency` opts into parallel execution (ADR #5); `None`/`1` = serial. `min_success` is the reduce-gate (fraction of items that must succeed).
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    body: Node
    concurrency: conint(ge=0) | None = None
    item_as: str
    kind: Kind3
    min_success: float | None = 1.0
    over: Ref


class Node5(BaseModel):
    """
    Serial iteration with side effects visible across items.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    body: Node
    item_as: str
    kind: Kind4
    over: Ref


class Node6(BaseModel):
    """
    Loop `body` while `cond` resolves truthy, bounded by `max_iters`. Each pass increments the `Addr::iteration` at this node.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    body: Node
    cond: Ref
    kind: Kind5
    max_iters: conint(ge=0)


class Node8(BaseModel):
    """
    Spawn one session per element of `sessions`, each running `body` against the named `actor`. `limit` (permits) serializes shared-resource access — this is the "poll under a center logic" pattern (DungeonGrid): set `permits = 1` on the env resource so sessions take turns.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    actor: str
    body: Node
    kind: Kind7
    limit: Limit | None = None
    sessions: Ref


class Node9(BaseModel):
    """
    Resume a previously-checkpointed session and run `body`.
    """

    inputs: dict[str, Ref] | None = Field(
        {},
        description='Inputs the node reads, resolved from the ledger before it runs.',
        validate_default=True,
    )
    outputs: dict[str, Ref] | None = Field(
        {},
        description='Outputs the node writes back into the ledger when it completes.',
        validate_default=True,
    )
    body: Node
    kind: Kind8
    session: Ref


class Node(
    RootModel[Node1 | Node2 | Node3 | Node4 | Node5 | Node6 | Node7 | Node8 | Node9]
):
    root: Node1 | Node2 | Node3 | Node4 | Node5 | Node6 | Node7 | Node8 | Node9 = Field(
        ..., description='A node = its kind plus its I/O wiring.'
    )


WorkflowSpec.model_rebuild()
Node4.model_rebuild()
Node5.model_rebuild()
Node6.model_rebuild()
Node8.model_rebuild()
Node9.model_rebuild()
